from django.urls import path
from .views import (
    RegisterView,
    VerifyEmail,
    LoginView,
    LogOut,
    OmniportLoginURLView,
    OmniportCallBackView,
    EventListCreateView,
    AlbumListCreateView,
    PhotoListCreateView,
    PhotoCommentListCreateView,
    PhotoLike,
    DownloadPhoto,
    AlbumPhotoManage,
    CreatePersonTag,
    RoleChangeRequestCreate,
    RoleChangeRequestList,
    RoleChangeRequestReview,
    PhotoUpload,
    MultiplePhotoUpload,
    PhotoMetaDataExtractionView,
    MyFavourite,
    MyAlbumView,
    MyTaggedView,
    AdminAssignRole,
    PhotoSearch,
    MeView,
)

urlpatterns =[
    path("auth/register", RegisterView.as_view(), name="register"),
    path("auth/login", LoginView.as_view(), name="login"),
    path("auth/logout", LogOut.as_view(), name="logout"),
    path("auth/verify-email", VerifyEmail.as_view(), name="verify-email"),
    path("auth/omniport-login-url", OmniportLoginURLView.as_view(), name="omniport-login-url"),
    path("auth/omniport-callback", OmniportCallBackView.as_view(), name="omniport-callback"),
    path("events/", EventListCreateView.as_view(), name="event-list-create"),
    path("albums/", AlbumListCreateView.as_view(), name="album-list-create"),
    path("photos/", PhotoListCreateView.as_view(), name="photo-list-create"),
    path("photos/<uuid:photo_id>/comments/", PhotoCommentListCreateView.as_view(), name="photo-comment-list-create"),
    path("photos/<uuid:photo_id>/like/", PhotoLike.as_view(), name="photo-like"),
    path("photos/<uuid:photo_id>/download/", DownloadPhoto.as_view(), name="photo-download"),   
    path("albums/<uuid:album_id>/photos/", AlbumPhotoManage.as_view(), name="album-manage"),
    path("tags/person/", CreatePersonTag.as_view(), name="create-person-tag"),
    path("role-requests/", RoleChangeRequestCreate.as_view(), name="role-request-create"),
    path("role-requests/admin", RoleChangeRequestList.as_view(), name="role-request-list"),
    path("role-requests/<uuid:role_request_id>/review", RoleChangeRequestReview.as_view(), name="role-request-review"),
    path("photos/upload", PhotoUpload.as_view(), name="photo-upload"),
    path("photos/bulk-upload", MultiplePhotoUpload.as_view(), name="multiple-photo-upload"),
    path("photos/<uuid:photo_id>/metadata-extraction", PhotoMetaDataExtractionView.as_view(), name="photo-metadata-extraction"),
    path("my/favourite", MyFavourite.as_view(), name="my-favourite"),
    path("my/albums", MyAlbumView.as_view(), name="my-albums"),
    path("my/tags", MyTaggedView.as_view(), name="my-tags"),
    path("admin/assign-role", AdminAssignRole.as_view(), name="admin-assign-role"),
    path("photos/search", PhotoSearch.as_view(), name="photo-search"),
    path("auth/me/", MeView.as_view(), name="me"),
]