# Generated by Django 5.2.1 on 2025-12-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='profile_pciture',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='photo_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_metadata', to='core.photo'),
        ),
    ]
