# Generated by Django 5.2.1 on 2025-12-09 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailotp_person_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmniportAccount',
            fields=[
                ('omniport_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('omniport_user_id', models.CharField(max_length=500, unique=True)),
                ('access_token', models.CharField(max_length=500, unique=True)),
                ('refresh_token', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omniport_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
