# Generated by Django 5.2.1 on 2025-12-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_persontag_content_type_persontag_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolechangerequest',
            old_name='id',
            new_name='request_id',
        ),
    ]
