# Generated by Django 5.2.1 on 2025-12-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_rolechangerequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontag',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='core.album'),
        ),
        migrations.AddField(
            model_name='persontag',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='core.events'),
        ),
        migrations.AlterField(
            model_name='persontag',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='core.photo'),
        ),
    ]
