# Generated by Django 5.2.1 on 2025-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_oauthstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
