# Generated by Django 5.2.1 on 2026-01-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_person_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file_path_thumbnail',
        ),
        migrations.AddField(
            model_name='photo',
            name='file_path_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='photos/compressed'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_path_original',
            field=models.ImageField(upload_to='photos/original'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_path_watermarked',
            field=models.ImageField(blank=True, null=True, upload_to='photos/watermarked'),
        ),
    ]
