# Generated by Django 5.2.1 on 2026-01-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_photo_file_path_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file_path_compressed',
            new_name='file_compressed',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file_path_original',
            new_name='file_original',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file_path_watermarked',
            new_name='file_watermarked',
        ),
    ]
