# Generated by Django 5.2.1 on 2026-01-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_file_path_compressed_photo_file_compressed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album_id',
        ),
    ]
