# Generated by Django 5.2.1 on 2026-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
