# Generated by Django 5.2.1 on 2026-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='omniport_user_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
