# Generated by Django 5.2.1 on 2026-01-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_person_omniport_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='omniport_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
